server_names = ['tor-hidden-doh']
listen_addresses = ['0.0.0.0:5353']
max_clients = 250
user_name = 'nobody'
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = true
odoh_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = true

ignore_system_dns=false
#force_tcp = false		#this would be necessary if we werent using DoH
http3 = false
http3_probe = false

timeout = 5000
keepalive = 20
blocked_query_response = 'refused'

log_level = 3
log_file = '/dev/stdout'
log_file_latest = true
use_syslog = false

cert_refresh_delay = 240
cert_ignore_timestamp = false
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false

bootstrap_resolvers = []

netprobe_timeout = 60
netprobe_address = ''
offline_mode = false

block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 10

cache = true

[query_log]
file = '/dev/null'				# for privacy
ignored_qtypes = ['DNSKEY', 'NS', 'AAAA', 'A', 'CNAME', 'TXT', 'MX']

[nx_log]
file = '/dev/null'				# for privacy
format = 'tsv'

[monitoring_ui]

enabled = true
listen_address = "0.0.0.0:9105"

username = "admin"
password = "prometheusmetrics"

tls_certificate = ""
tls_key = ""

enable_query_log = false
privacy_level = 2
max_query_log_entries = 100
max_memory_mb = 1
prometheus_enabled = true
prometheus_path = "/metrics"

[static]
[static.tor-hidden-doh]   #127.0.0.1, one.one.one.one, /dns-query
	stamp = 'sdns://AgcAAAAAAAAACTEyNy4wLjAuMQAPb25lLm9uZS5vbmUub25lCi9kbnMtcXVlcnk'
