services:
  moledns:
    restart: unless-stopped
    build: ./
    ports:
    # you can remove this section if you only plan to provide services to other containers
      #- "853:53/tcp"		# not implemented
      - "127.0.0.2:53:53/udp"
      # for the dnscrypt browser UI
      - "9104:9104"
      # for the dnscrypt browser UI - hidden proxy
      - "9105:9105"
      # hidden metrics
      - "9100"
      # public metrics
      - "9200"
    expose:
    # useful if you plan on providing services to other containers
      - "53/udp"
      - "9100"
      - "9200"
    volumes:
      - ./resolv.conf:/etc/resolv.conf:ro
    healthcheck:
      test: ["CMD-SHELL", 'dig @127.0.0.1 -p 53 cloudflare.com A +short > /dev/null']
      interval: 15s
      timeout: 5s
      retries: 10
#    networks:
#      - dns_net
    cap_add:
      - NET_ADMIN
      # we need admin networking privileges in the container to do some things
